### ISSUE TITLE
Pushing to Heroku

### ISSUE THREAD

**Issue by patmisch** [theleoborges/app_constants#2]
After pushing to heroku, app crashes (H10 error)

**Comment by theleoborges** [comment]
Hey, could you provide a little more about the error? Some direct log from heroku perhaps?

I have several apps on Heroku and they've been working fine since the last update.

As a side node, are you using the new "raise_exception" option? If so, that will raise an exception to inform you you're trying to access a constant/environment that doesn't exist.

Cheers

**Comment by patmisch** [comment]
Looks like it is working now. Must have been something fishing going on with
my heroku instance. Sorry for the bother and thanks for the code!

**Comment by theleoborges** [comment]
No Worries!

Glad it's working now! :)

Cheers
